# Copyright (c) 2022 Huawei Technologies Co., Ltd.
# Licensed under CC BY-NC-SA 4.0 (Attribution-NonCommercial-ShareAlike 4.0 International) (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://creativecommons.ours/licenses/by-nc-sa/4.0/legalcode
#
# The code is released for academic research use only. For commercial use, please contact Huawei Technologies Co., Ltd.
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# This repository was forked from https://github.com/openai/guided-diffusion, which is under the MIT license

attention_resolutions: 16,8,4
class_cond: false
diffusion_steps: 1000
learn_sigma: false
noise_schedule: cosine
num_channels: 128
num_head_channels: 64
num_heads: 4
num_res_blocks: 3
resblock_updown: false
use_fp16: false
use_scale_shift_norm: true
classifier_scale: 4.0
lr_kernel_n_std: 2
num_samples: 100
show_progress: true
timestep_respacing: '250'
use_kl: false
predict_xstart: false
rescale_timesteps: false
rescale_learned_sigmas: false
classifier_use_fp16: false
classifier_width: 128
classifier_depth: 2
classifier_attention_resolutions: 32,16,8
classifier_use_scale_shift_norm: true
classifier_resblock_updown: true
classifier_pool: attention
num_heads_upsample: -1
channel_mult: ''
dropout: 0.0
use_checkpoint: false
use_new_attention_order: false
clip_denoised: true
use_ddim: false
latex_name: RePaint
method_name: Repaint
image_size: 128
model_path: ./ckpt/ours/ema_0.9999_500000.pt
name: celeba128_ours
inpa_inj_sched_prev: true
n_jobs: 4
print_estimated_vars: true
inpa_inj_sched_prev_cumnoise: false
schedule_jump_params:
  t_T: 250
  n_sample: 2
  jump_length: 10
  jump_n_sample: 10
data:
  eval:
    celeba_thick_mask:
      mask_loader: true
      gt_path: ./data/datasets/gts/celeba
      mask_path: ./data/datasets/gt_keep_masks/thick
      image_size: 128
      class_cond: false
      deterministic: true
      random_crop: false
      random_flip: false
      return_dict: true
      drop_last: false
      batch_size: 8
      return_dataloader: true
      max_len: 100
      paths:
        srs: ./log/celeba128_ours/thick/inpainted
        lrs: ./log/celeba128_ours/thick/gt_masked
        gts: ./log/celeba128_ours/thick/gt
        gt_keep_masks: ./log/celeba128_ours/thick/gt_keep_mask